# Generated by Django 3.2.9 on 2021-12-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211202_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='uid',
            field=models.CharField(default='non', max_length=300, unique=True),
            preserve_default=False,
        ),
    ]
