# Generated by Django 3.2.9 on 2021-12-02 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_accounts_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='entToken',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='riotAuth',
            field=models.CharField(max_length=1000),
        ),
    ]
