# Generated by Django 3.2.9 on 2021-12-04 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_uid_accounts_unique'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='entToken',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='accounts',
            old_name='riotAuth',
            new_name='hashedPass',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='unique',
        ),
        migrations.AlterField(
            model_name='accounts',
            name='userName',
            field=models.CharField(default='None', max_length=150),
        ),
    ]
