# Generated by Django 3.2.9 on 2021-12-04 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20211204_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='email',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='hashedPass',
            field=models.CharField(max_length=200),
        ),
    ]
